[package]
name = "gpu-post"
version = "0.1.0"
authors = ["spacemesh <devteam@spacemesh.io>"]
edition = "2018"

[build-dependencies]
rustc_version = "0.2"

[dependencies]

[lib]
path = "src/lib.rs"
name = "gpu_post_bindings"

[[bin]]
path = "src/main.rs"
name = "gpu-binding-test"
