[package]
name = "pos-api"
version = "0.1.0"
authors = ["avive <avive@spacemesh.io>"]
description = "proof of space server api"
edition = "2018"

[build-dependencies]
tonic-build = "0.3"

[dependencies]
tonic = "0.3"
prost = "0.6"
chrono = "*"
hex = "*"